### ISSUE TITLE
manuscript doesn't render

### ISSUE THREAD

**Issue by andreashandel** [Nwgreen6283/NathanGreenslit-MADA-Project#1]
this fails
resulttable=readRDS("../../results/summarytable.rds")

Please fix by using the here() package. See here for information:
https://andreashandel.github.io/MADAcourse/Data_Analysis_Structure.html

Once it is fixed, I'll take another look and provide feedback as suitable.

**Comment by Nwgreen6283** [comment]
Commented out old code from template. File should now render!
